export const FETCH_LOCATION_REQUEST = 'FETCH_LOCATION_REQUEST';
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';
export const SET_REGION = 'SET_REGION';
export const SET_INIT_REGION = 'SET_INIT_REGION';
export const FETCH_ADDRESS_REQUEST = 'FETCH_ADDRESS_REQUEST';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_ERROR = 'FETCH_ADDRESS_ERROR';
export const FETCH_CURRENT_ADDRESS_SUCCESS = 'FETCH_CURRENT_ADDRESS_SUCCESS';

export const FETCH_DESTINATION_REQUEST = 'FETCH_DESTINATION_REQUEST';
export const FETCH_DESTINATION_SUCCESS = 'FETCH_DESTINATION_SUCCESS';
export const FETCH_DESTINATION_ERROR = 'FETCH_DESTINATION_ERROR';
export const CHOOSE_DESTINATION_ON_MAP = 'CHOOSE_DESTINATION_ON_MAP';
export const FETCH_DIRECTIONS_REQUEST = 'FETCH_DIRECTIONS_REQUEST';
export const FETCH_DIRECTIONS_SUCCESS = 'FETCH_DIRECTIONS_SUCCESS';
export const FETCH_DIRECTIONS_ERROR = 'FETCH_DIRECTIONS_ERROR';
export const FETCH_PICKUP_REQUEST = 'FETCH_PICKUP_REQUEST';
export const FETCH_PICKUP_SUCCESS = 'FETCH_PICKUP_SUCCESS';
export const FETCH_PICKUP_ERROR = 'FETCH_PICKUP_ERROR';

export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_ERROR = 'FETCH_CARS_ERROR';

export const FETCH_BEST_CAR_REQUEST = 'FETCH_BEST_CAR_REQUEST';
export const FETCH_BEST_CAR_SUCCESS = 'FETCH_BEST_CAR_SUCCESS';
export const FETCH_BEST_CAR_ERROR = 'FETCH_BEST_CAR_ERROR';

export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';

export const CANCEL_RIDE = 'CANCEL_RIDE';
export const BOOK_RIDE = 'BOOK_RIDE';
export const MOVE_CAR = 'MOVE_CAR';
export const RIDE_FINISHED = 'RIDE_FINISHED';
export const CAR_POSITION_SET = 'CAR_POSITION_SET';
export const AT_PICKUP = 'AT_PICKUP';
export const AFTER_PICKUP = 'AFTER_PICKUP';

export const RIDE_ADDED = 'RIDE_ADDED';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_SOCKET = 'SET_SOCKET';

export const FETCH_RIDES_SUCCESS = 'FETCH_RIDES_SUCCESS';

